from enum import Enum

class Keys( Enum ):
    KEY_MOVE_FORWARD = 1
    KEY_MOVE_BACKWARD = 2
    KEY_MOVE_TO_THE_LEFT = 3
    KEY_MOVE_TO_THE_RIGHT = 4
    KEY_ROTATE_CLOCKWISE = 5
    KEY_ROTATE_COUNTERCLOCKWISE = 6
    KEY_FIRE = 7
